### ISSUE TITLE
oauth.provider for AzureAD

### ISSUE THREAD

**Issue by buerklj** [mblaschke/devops-console#8]
Hi,

the oauth.provider URI for AzureAD is hardcoded [here](https://github.com/mblaschke/devops-console/blob/c7963a345e1eb8f6497adb04b53a64b88fa54042/services/oauth.go#L128) I believe. Hence it will not work for other Azure Clouds eg. Azure China Cloud 

Regards JB

**Comment by mblaschke** [comment]
set `OAUTH_AUTH_URL` to eg `https://sts.windows.net/{tenantID}/`
